/// Flutter icons CustomGolf
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomGolf
///      fonts:
///       - asset: fonts/CustomGolf.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomGolf {
  CustomGolf._();

  static const _kFontFam = 'CustomGolf';

  static const IconData golfbag = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ironicon = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData puttericon = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData drivericon = const IconData(0xe803, fontFamily: _kFontFam);
}
